### ISSUE TITLE
Add to F-Droid

### ISSUE THREAD

**Issue by inson1** [flutter/gallery#1020]
### Description

Title

**Comment by parlough** [comment]
Thanks for the suggestion! Due to https://github.com/flutter/gallery/issues/1072, we likely won't be able to do this. If someone else would like to maintain an F-Droid version though, they could if they follow the repository's [LICENSE](https://github.com/flutter/gallery/blob/main/LICENSE) and [Flutter's Brand Guidelines](https://docs.flutter.dev/brand).

You can also find an older version of the gallery hosted online at https://gallery-flutter-dev.web.app.
