### ISSUE TITLE
A few questions 

### ISSUE THREAD

**Issue by DeadlyMissile** [flutter/gallery#178]
I have a few question if you don’t mind :D 
1- On main.dart, the initialRoute is null. So what happens exactly?
2- On main.dart, you are overriding the themes platform with GalleryOptions.platform. Why is that?
3- Why are you using RegEx on routes? First time seeing it done is this way

**Comment by perclasson** [comment]
Thanks for your questions - in the future I recommend asking in the appropriate Flutter discord channels as the issues here should be used for bugs and not questions.

1. If initialRoute is null, the default value of '/' is used. See documentation for [WidgetsApp](https://api.flutter.dev/flutter/widgets/WidgetsApp/initialRoute.html).
2. So that we can change the platform in the settings panel, to make it easy to test platform mechanics of other platforms.
3. See this Medium post: https://api.flutter.dev/flutter/widgets/WidgetsApp/initialRoute.html

Hopefully that answers your questions, I'll close the issue as fixed as I think that should answer it.
