### ISSUE TITLE
A Gallery App corresponding to Stable Release

### ISSUE THREAD

**Issue by limbouser** [flutter/gallery#196]
Out of all the releases, can I find a Gallery app version which is compatible with latest Stable release? Isn't it a good suggestion to keep a version of the Gallery that can be run on Stable?

**Comment by guidezpl** [comment]
That is a good suggestion, thanks! When the gallery was in development (not too long ago), we initially targeted the stable channel. For a number of reasons, we switched to the master channel. For example, we were interesting in having the gallery run on a breadth of platforms. Platforms are at different maturity stages, so that is only possible by targeting the master (or dev) channel. This also allowed us to make refinements and improvements to focus-handling and localization support.

Anyway, I anticipate that the first stable release the gallery will support will be the upcoming one. From my minimal testing, the gallery runs on the dev channel (1.20.0-2.0.pre). Expect the gallery to be runnable on the beta channel in the coming weeks, and then stable after that!

Since it's just a waiting game for now, I'll close this issue.

**Comment by avinashKaitheri** [comment]
Do we have a solution for this since a newer stable version hhas come out? @guidezpl
