### ISSUE TITLE
Ensure sliders have useful a11y labels

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#226]
It would be nice if these sliders had accessibility labels, just as an example for developers to follow. Currently, screen readers only read the value

**Comment by guidezpl** [comment]
Blocked on framework changes. https://github.com/flutter/flutter/pull/63524 would allow us to fix this

**Comment by clocksmith** [comment]
Right now the screen reader announces the value. After this change, would it first announce that the focused element is a slider, then announce the value?

**Comment by guidezpl** [comment]
I believe so.

**Comment by apomalyn** [comment]
I'm very new to open source and I don't see any CONTRIBUTING.md inside the repo so I will just ask. Can I take this issue?
If yes, what is the correct process to contribute?

Thanks :D

**Comment by guidezpl** [comment]
Hi @apomalyn. Sure! I've created an upstream bug that (I believe) you can assign yourself to flutter/flutter#67396. The CONTRIBUTING.md for flutter/flutter applies

**Comment by apomalyn** [comment]
Hi @guidezpl ! Thanks, 😄  I can't assign the issue to myself but it's not a problem, I will drop a comment there to signify my interest on the issue.

To be sure to correctly understand the issue, the a11y message about the slider currently read only the value of the slider and we would like to have a nice message like "Slider value is XX"?
This problem is from the Flutter framework, not gallery, this is why you opened an issue there. Right?

Sorry if my questions are silly I'm not really good in English and I don't want to want you loose time by reviewing useless PR 😅

**Comment by guidezpl** [comment]
Yes this is a framework PR, but it's not about changing the label manually. Rather, setting `Semantics.slider` [docs](https://master-api.flutter.dev/flutter/widgets/Semantics-class.html) to `true` for those three widgets

**Comment by apomalyn** [comment]
Thank you a lot!
