### ISSUE TITLE
Change channel to beta or stable

### ISSUE THREAD

**Issue by guidezpl** [flutter/gallery#593]
Should consider now that development has slowed, we don't have such a great need to use the master channel.

Using stable would mean devs wouldn't have to switch channels (common issue) to run the gallery.

One consideration is that flutter/flutter uses the gallery for tests, and is pinned in two places
* https://github.com/flutter/tests/blob/master/registry/flutter_gallery.test
* https://github.com/flutter/flutter/blob/master/dev/devicelab/lib/versions/gallery.dart

**Comment by wolkenschieber** [comment]
I vote for `stable` channel.

**Comment by parlough** [comment]
I'm going to close this due to https://github.com/flutter/gallery/issues/1072, but for those reading: Do note that the current form of the app does run on the current stable (3.16.7).

For your own apps, I highly encourage you consider developing and running your app on the `beta` channel. Releases on the `beta` channel are well tested and enable you to get fixes, performance improvements, and new features faster! It's much easier to make incremental updates as well =D 

If you'd like to learn more about the channels, particularly the `beta` channel watch this new video on [When to use the Flutter beta channel](https://youtu.be/ipaVjs-_3iQ)!
