### ISSUE TITLE
Question about larger accessibility display size

### ISSUE THREAD

**Issue by kw214** [flutter/gallery#880]
In my application, the UI will overflow out of the screen, when the `display size` is modified to the maximum value in the settings of the Android emulator. I found that the `flutter gallery` does not have this kind of problem, how does the `flutter gallery` deal with it?

**Comment by guidezpl** [comment]
That's a good question. This is done is a few ways:
- Testing at maximum text scale: In the options in the upper-right, we can simulate large text and identify overflow issues
- Use of flexible containers: rather than `Column` and `Row`, the gallery uses `SingleChildScrollView`, `ListView`, and `Wrap` and other flexible layout widgets, to allow elements to be scrolled or to wrap them to another line when necessary
- Capping text scale: In some rare cases, [limiting the maximum size at which text can display](https://github.com/flutter/gallery/blob/dc193185c97d25878cf886d47565986f422567fe/lib/layout/text_scale.dart#L39).
- Use of `Expanded` widgets to control how much space widgets can take
- Use of `overflow` properties to sometimes hide or replace overflow with "..."

These are the techniques I can think of.
