### ISSUE TITLE
Focus and keyboard traversal might be broken

### ISSUE THREAD

**Issue by clocksmith** [flutter/gallery#89]
**Describe the bug**
Try navigating with the keyboard on the main screen. Nothing gets highlighted. This might be a regression in flutter/flutter because it used to work.

**Comment by rami-a** [comment]
Yeah this definitely used to work

**Comment by gspencergoog** [comment]
It's not actually focus that is broken, it is the focus highlights: the app seems to think it is in "touch" mode, even when it's seen a mouse/keyboard.

It is because of this change I made recently, but I'm not sure what the failure there is yet: https://github.com/flutter/flutter/pull/52990

I'll see if I can come up with a fix.

**Comment by guidezpl** [comment]
Thanks, it works again
