### ISSUE TITLE
[Question] Flutter Gallery assets structure management 

### ISSUE THREAD

**Issue by polarby** [flutter/gallery#980]
Hey there, 
I am fully aware that questions are intended to be asked on StackOverflow, but as my question is directly targeted to this repository, I find it reasonable to reach out to you guys directly. On my way to improve my app (espacially the inital loading of flutter web) i have noticed following practices in the flutter gallery repository, that spiked my interest:

* I have seen that the gallery has moved each study to an external `flutter_gallery_assets` plugin and then seemingly importing them as normal asset. This raised my interest, if the assets are only put into a seperate plugin for structual purposes or if performance improvements play also a part - even after [normal asset import](https://github.com/flutter/gallery/blob/18f1e8e2d4b367b2bf24269110793ed1b33c770a/pubspec.yaml#L109) in the `pubspec.yaml` file.

* I have also seen that you make use of `deferred-components` in the `pubspec.yaml` file. There you seem to be importing the `crane` study. Although i have read that this option is only working on android, i am still puzzled how you were able to make the imports still work on web -  and if this kind of import also has influence on the performance on other platforms. 

**My question:**
Was the flutter's initial load speed (especially web) substantially influenced by moving assets from the main project to an asset plugin? And is that a practice that should be implemented on every well structured project?

**Comment by guidezpl** [comment]
1. `flutter_gallery_assets` exists because it's used by multiple projects, not for any performance reason. Its assets are treated just like any other asset, just in a different folder. In fact, it's a bit more cumbersome because pubspec.yaml currently doesn't support wildcards for package based assets and we therefore have to list all assets.

2. Deferred loading is supported on Android directly (separate app modules) and implicitly on web and other platforms. I'm not sure about the impact, but it does allow us to reduce the bundle size. See https://medium.com/flutter/optimizing-performance-in-flutter-web-apps-with-tree-shaking-and-deferred-loading-535fbe3cd674 for more
